# @host=http://localhost:3000
@host=http://localhost:4200/api
# @host=https://budget-assistant.dtkcp.duckdns.org/api
@year=2024
@month=12


GET {{host}}/budgets/{{year}}/{{month}}
###

# Buckets group
GET {{host}}/transactions/fc3825fd-b982-4b72-b768-5b30844cf832/{{year}}/{{month}}
###

# Savings and Investments group
GET {{host}}/transactions/a137772f-cf2f-4089-9432-822d2ddc1466/{{year}}/{{month}}
###

GET {{host}}/accounts
###

GET {{host}}/accounts?includeCurrentBalance
###

GET {{host}}/accounts?name=Savings&includeCurrentBalance
###
