@host=http://localhost:3000
@year=2024
@month=12


GET {{host}}/budgets/{{year}}/{{month}}
###

GET {{host}}/transactions/Buckets/{{year}}/{{month}}
###


GET {{host}}/transactions/Investments%20and%20Savings/{{year}}/{{month}}
###

GET {{host}}/accounts
###

GET {{host}}/accounts?includeCurrentBalance
###

GET {{host}}/accounts?name=Savings&includeCurrentBalance
###
